java:
  applicationPort: 4011
  aadIdentityName: divorce
  image: hmctspublic.azurecr.io/div/cfs:latest
  ingressHost: "div-cfs-{{ .Values.global.environment }}.{{ .Values.global.environment }}.platform.hmcts.net"
  autoscaling:
    enabled: true
    maxReplicas: 4
    targetCPUUtilizationPercentage: 80 # Default is 80% target CPU utilization
  environment:
    DOCUMENT_MANAGEMENT_STORE_URL: "http://dm-store-{{ .Values.global.environment }}.{{ .Values.global.environment }}.platform.hmcts.net"
  keyVaults:
    div:
      secrets:
        - AppInsightsInstrumentationKey
