java:
  applicationPort: 4011
  aadIdentityName: divorce
  image: hmctspublic.azurecr.io/div/cfs:latest
  ingressHost: "div-cfs-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
  autoscaling:
    enabled: true
    maxReplicas: 4
    targetCPUUtilizationPercentage: 80 # Default is 80% target CPU utilization
  environment:
    DOCUMENT_MANAGEMENT_STORE_URL: "http://dm-store-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
  keyVaults:
    div:
      secrets:
        - name: AppInsightsInstrumentationKey
          alias: azure.application-insights.instrumentation-key
        - name: app-insights-connection-string
          alias: app-insights-connection-string
