java:
  applicationPort: 4011
  aadIdentityName: divorce
  image: hmctspublic.azurecr.io/div/cfs:latest
  ingressHost: "div-cfs-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
  environment:
    DOCUMENT_MANAGEMENT_STORE_URL: "http://dm-store-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
  keyVaults:
    div:
      secrets:
        - AppInsightsInstrumentationKey
