---
version: '3'

services:
    case-formatter-service:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                - http_proxy
                - https_proxy
                - no_proxy
        healthcheck:
            disable: true
        ports:
            - 4011:4011

