info:
  app:
    name: ${spring.application.name}

spring:
  application:
    name: div-cfs
  resources:
    static-locations:

server:
  port: 4011

idam:
  api:
    url: ${IDAM_API_BASEURL:http://localhost:4503}
    port: 4503
    health:
      context-path: /health

document:
  management:
    store:
      url: ${DOCUMENT_MANAGEMENT_STORE_URL:http://localhost:5006}

cohort: onlineSubmissionPrivateBeta

court:
  details: "{
              \"eastMidlands\":{
                \"divorceCentre\":\"East Midlands Regional Divorce Centre\",
                \"courtCity\":\"Nottingham\",
                \"poBox\":\"PO Box 10447\",
                \"postCode\":\"NG2 9QN\",
                \"openingHours\":\"Telephone Enquiries from: 8.30am to 5pm\",
                \"email\":\"eastmidlandsdivorce@hmcts.gsi.gov.uk\",
                \"phoneNumber\":\"0300 303 0642\",
                \"siteId\":\"AA01\"
              },
              \"westMidlands\":{
                \"divorceCentre\":\"West Midlands Regional Divorce Centre\",
                \"courtCity\":\"Stoke-on-Trent\",
                \"poBox\":\"PO Box 3650\",
                \"postCode\":\"ST4 9NH\",
                \"openingHours\":\"Telephone Enquiries from: 8.30am to 5pm\",
                \"email\":\"westmidlandsdivorce@hmcts.gsi.gov.uk\",
                \"phoneNumber\":\"0300 303 0642\",
                \"siteId\":\"AA02\"
              },
              \"southWest\":{
                \"divorceCentre\":\"South West Regional Divorce Centre\",
                \"courtCity\":\"Southampton\",
                \"poBox\":\"PO Box 1792\",
                \"postCode\":\"SO15 9GG\",
                \"openingHours\":\"Telephone Enquiries from: 8.30am to 5pm\",
                \"email\":\"sw-region-divorce@hmcts.gsi.gov.uk\",
                \"phoneNumber\":\"0300 303 0642\",
                \"siteId\":\"AA03\"
              },
              \"northWest\":{
                \"divorceCentre\":\"North West Regional Divorce Centre\",
                \"divorceCentreAddressName\":\"Liverpool Civil & Family Court\",
                \"courtCity\":\"Liverpool\",
                \"street\":\"35 Vernon Street\",
                \"postCode\":\"L2 2BX\",
                \"openingHours\":\"Telephone Enquiries from: 8.30am to 5pm\",
                \"email\":\"family@liverpool.countycourt.gsi.gov.uk\",
                \"phoneNumber\":\"0300 303 0642\",
                \"siteId\":\"AA04\"
              },
              \"serviceCentre\": {
                \"serviceCentreName\": \"Courts and Tribunals Service Centre\",
                \"divorceCentre\": \"East Midlands Regional Divorce Centre\",
                \"courtCity\": \"Nottingham\",
                \"poBox\": \"PO Box 10447\",
                \"postCode\": \"NG2 9QN\",
                \"openingHours\": \"Telephone Enquiries from: 8.30am to 5pm\",
                \"email\": \"divorce@justice.gov.uk\",
                \"phoneNumber\": \"0300 303 0642\",
                \"siteId\": \"CTSC\"
              }
           }"

http:
  connect:
    timeout: 60000
    request:
      timeout: 60000

health:
    check:
        http:
            connect:
                timeout: 5000
                request:
                    timeout: 5000

documentation:
  swagger:
    enabled: true

# GENERAL SPRING BOOT ACTUATOR CONFIG
# Context path for Spring Boot Actuator endpoints
# Allow actuator endpoints to be accessed without requiring authentication
# Enable default health indicators
# Enable disk space health check
management:
  endpoint:
    health:
      show-details: "ALWAYS"
      cache:
        time-to-live: 4000
  endpoints:
    web:
      base-path: /
      path-mapping:
        health: health
      exposure:
        include: info, health, metrics


logging:
  level:
    org.springframework.web: ERROR
    uk.gov.hmcts.reform.divorce.casedataformatterservice: DEBUG
  pattern:
    console: "%d{yyyy-MMM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{15} - %msg%n"

azure:
  app_insights_key: ${APPINSIGHTS_INSTRUMENTATIONKEY:false}
