# Example file - DO NOT PUT SECRETS HERE - make a copy as application-aat.yaml (git ignored)

document:
    management:
        store:
            url: ${DOCUMENT_MANAGEMENT_STORE_URL:http://dm-store-aat.aat.platform.hmcts.net}
